/* Lohi Bher report: plain-words glossary.
   One entry per code the chapters may wrap in <abbr class="ind" data-ind="KEY">.
   `name` is the official label. `plain` is one sentence a sixth grader can read.
   Moves m1..m10 come from build/fidelity_moves_by_session.json (Raheela: Grade 3 English,
   Unit 6 "Game On!", 8 steps. Saima: Grade 2 English, "Pinky and Jojo", 10 steps). */
window.RUMI_GLOSSARY = {
  /* ---- B: did the lesson follow its plan ---- */
  B1:  { name: "Instructional Clarity & Learning Objectives",
         plain: "Did the teacher say clearly what the children would learn today, and did the lesson stick to it?" },
  B2:  { name: "Lesson Structure & Sequence",
         plain: "Did the lesson go in a sensible order, with a start, a middle and an end?" },
  B3:  { name: "Activities & Tasks Alignment",
         plain: "Did the tasks the children did actually help them reach the lesson's goal?" },
  B4:  { name: "Activation of Prior Knowledge",
         plain: "Did the teacher first remind children of what they already knew before adding something new?" },
  B5:  { name: "Meaningful & Real-World Connections",
         plain: "Did the teacher link the lesson to real life, like things children see at home or outside?" },
  B6:  { name: "Differentiation / Catering to Learning Levels",
         plain: "Did the teacher give easier or harder work to children who needed it, instead of one task for everyone?" },
  B7:  { name: "Use of Taleemabad Lesson Plan",
         plain: "Did the teacher actually use the Taleemabad lesson plan in class, not just have it?" },
  B8:  { name: "Use of Prescribed Resources",
         plain: "Did the teacher use the things the plan asked for, like the textbook page, pictures or cards?" },
  B9:  { name: "Time on Task / Time on Learning",
         plain: "How much of the period was spent actually learning, rather than waiting or settling down?" },
  B10: { name: "Lesson Closure & Consolidation",
         plain: "Did the lesson end with a short wrap-up that pulled the main idea together?" },

  /* ---- C: teaching moves that make a big difference ---- */
  C1:  { name: "Quality Questioning (Bloom's Aligned)",
         plain: "Did the teacher ask questions that make children think, not only remember?" },
  C2:  { name: "Responsive Re-explanation & Adaptive Teaching",
         plain: "When children did not get it, did the teacher explain it again in a new way?" },
  C3:  { name: "Effective Feedback",
         plain: "Did the teacher tell children what they did well and what to fix, not just say right or wrong?" },
  C4:  { name: "Equitable Participation",
         plain: "Did every child get a turn, or only the few at the front who always raise their hands?" },
  C5:  { name: "Student Agency & Voice",
         plain: "Did children get to share their own ideas and make some choices in the lesson?" },
  C6:  { name: "Classroom Management & Routines",
         plain: "Was the class calm and organised, with clear routines so little time was lost?" },
  C7:  { name: "Positive & Supportive Learning Environment",
         plain: "Did children feel safe to try, and did the teacher stay kind and encouraging?" },
  C8:  { name: "Modeling, Scaffolding & Problem-Solving",
         plain: "Did the teacher show how to do it first, then help step by step, then let children try alone?" },
  C9:  { name: "Collaborative Learning",
         plain: "Did children work together in pairs or groups in a way that really helped them learn?" },
  C10: { name: "Integration of Taleemabad Technology",
         plain: "Did the teacher use Taleemabad's videos, quizzes or app in the lesson?" },
  C11: { name: "Self & Peer Assessment Facilitation",
         plain: "Did children check their own work or a partner's work, instead of only the teacher checking?" },
  C12: { name: "Classroom Resources & Space for Collaboration",
         plain: "Was the room set up with materials and seating that let children work together?" },

  /* ---- D: what the children were doing ---- */
  D1:  { name: "Active Participation Rate",
         plain: "How many of the children were joining in, answering, or working, rather than sitting quietly?" },
  D2:  { name: "Cognitive Engagement Level (Bloom's)",
         plain: "Were children only repeating facts, or also explaining, comparing and creating?" },
  D3:  { name: "Student-to-Student Interaction",
         plain: "Did children talk to each other about the work, not only to the teacher?" },
  D4:  { name: "Student Confidence & Risk-Taking",
         plain: "Were children brave enough to try an answer even when they were not sure?" },
  D5:  { name: "On-Task Behavior During Independent Work",
         plain: "When children worked alone, did they keep working or drift off?" },
  D6:  { name: "Student Use of Learning Materials",
         plain: "Did children actually use the books, cards or tools in front of them?" },
  D7:  { name: "Inclusivity of Engagement",
         plain: "Were quieter children, girls and boys, and children who struggle all included?" },

  /* ---- F: does the teacher know the subject ---- */
  F1:  { name: "Content Accuracy",
         plain: "Was everything the teacher taught correct?" },
  F2:  { name: "Use of Academic Language",
         plain: "Did the teacher use the proper subject words, like 'noun' or 'fraction', and explain them?" },
  F3:  { name: "Anticipation of Student Misconceptions",
         plain: "Did the teacher spot the mistakes children usually make and deal with them?" },
  F4:  { name: "Depth of Explanation",
         plain: "Did the teacher explain why something is true, not only what the answer is?" },
  F5:  { name: "Subject-Specific Pedagogy: Math",
         plain: "Did the teacher use good ways of teaching maths, like showing with objects before numbers?" },
  F6:  { name: "Subject-Specific Pedagogy: Science",
         plain: "Did the teacher use good ways of teaching science, like letting children observe and test?" },
  F7:  { name: "Subject-Specific Pedagogy: Literacy/Language",
         plain: "Did the teacher use good ways of teaching reading and words, like sounding out and reading aloud?" },
  F8:  { name: "Cross-Curricular Connections",
         plain: "Did the teacher link this subject to another one, like using maths in a science lesson?" },

  /* ---- moves: one step the lesson plan asks the teacher to do ---- */
  m1:  { name: "Move 1, warm up",
         plain: "Step 1 of the plan. Raheela: children in pairs say the three ways to learn a new word out loud, then swap roles. Saima: point to the picture icons and have children explain 'sparkling' and 'whispered' to a partner in their own words." },
  m2:  { name: "Move 2, the hook",
         plain: "Step 2 of the plan, the bit that grabs attention. Raheela: ask about a hard task and whether you give up or keep going, then bring in the five new words. Saima: tell the story of the shiny door and the three confused visitors, and ask why they looked confused." },
  m3:  { name: "Move 3, board set-up",
         plain: "Step 3 of the plan, done before class starts. Raheela: write the five words and a three-column table on the board. Saima: write the heroes' names and put their pictures on the board. A recording cannot show whether this happened." },
  m4:  { name: "Move 4, teacher shows how",
         plain: "Step 4 of the plan. Raheela: teach the word 'wobble', show it with a hand movement, fill in the word bank and write one sentence. Saima: read the story on page 42 aloud and point out the three names as the answer to WHO." },
  m5:  { name: "Move 5, teach the idea",
         plain: "Step 5 of the plan. Raheela: the whole class builds word-bank entries for 'whoosh' and 'tiptoe', then pairs make sentences while the teacher walks around. Saima: teach 'sunny' from the '-un' word family, and explain WHO is a person, WHERE is a place, WHY is a reason." },
  m6:  { name: "Move 6, practice",
         plain: "Step 6 of the plan. Raheela: children work alone for 9 minutes, matching 'exclaim' to a picture, checking the five words with a partner and writing a 'chilly' sentence. Saima: read the story again together, find 'Pakistan' as the '-an' word, and stop to ask why Pinky whispered." },
  m7:  { name: "Move 7, check what stuck",
         plain: "Step 7 of the plan. Raheela: a quick exit check in one of three forms, a 'wobble' sentence, a 'chilly' multiple-choice question or the 'exclaim' textbook task. Saima: pairs think of another Pakistani hero and one reason, while the teacher checks every pair." },
  m8:  { name: "Move 8, on your own",
         plain: "Step 8 of the plan. Raheela: optional homework, ask a family member what 'whoosh' means and compare it with the book. Saima: three problems each child answers alone, with easier and harder versions for different children." },
  m9:  { name: "Move 9, exit ticket",
         plain: "Step 9 of the plan. Saima: a short exit ticket in one of three forms so the teacher knows who got it. Raheela's plan had only eight steps, so it has no move 9." },
  m10: { name: "Move 10, homework",
         plain: "Step 10 of the plan, optional. Saima: children ask a family member which Pakistani hero they admire and why, and write it down. Raheela's plan had only eight steps." },

  /* ---- other codes ---- */
  FICO: { name: "FICO observation rubric",
          plain: "The 37-point checklist NIETE coaches in Islamabad use when they watch a lesson, in four parts: B did the lesson follow its plan, C strong teaching moves, D how children took part, F how well the teacher knows the subject, each point scored 1 to 4." },
  NPS:  { name: "Net promoter score",
          plain: "A score from minus 100 to plus 100 that answers one question, would you recommend this to a colleague?" },
  SLO:  { name: "Student learning outcome",
          plain: "The goal for the lesson, what children should be able to do by the end." },
  LP:   { name: "Lesson plan",
          plain: "The written plan for one lesson, with the steps the teacher will follow." },
  ICT:  { name: "Islamabad Capital Territory",
          plain: "The federal schools in and around Islamabad." },
  NIETE: { name: "National Institute of Excellence in Teacher Education",
          plain: "The federal teacher-training institute that runs this programme." },
  FDE:  { name: "Federal Directorate of Education",
          plain: "The government office that runs the federal schools and sets the exam." },
  MCP:  { name: "Governed data connection",
          plain: "The safe, rule-checked way our team asks the database for numbers, so everyone gets the same answer." },
  fidelity: { name: "Lesson-plan fidelity",
          plain: "How closely the lesson followed its plan, the B score, worked out from the moves." },

  /* ---- verdicts on a move ---- */
  done:      { name: "Done", plain: "The teacher did this step the way the plan asked." },
  partly:    { name: "Partly", plain: "The teacher did some of this step but not all of it." },
  not_done:  { name: "Not done", plain: "This step did not happen." },
  substituted_better: { name: "Substituted better",
          plain: "The teacher did something different that served the same goal at least as well." },
  cant_judge: { name: "Can't judge",
          plain: "The recording cannot show it, for example something written on the board before class." }
};
/* aliases so either spelling of a verdict key works */
window.RUMI_GLOSSARY.executed = window.RUMI_GLOSSARY.done;
window.RUMI_GLOSSARY.partial = window.RUMI_GLOSSARY.partly;
window.RUMI_GLOSSARY.not_adjudicable = window.RUMI_GLOSSARY.cant_judge;
