/* GGPS Kalas, 7 Oct 2026: chart specs for charts.js (format: CHARTS_SPEC.md). Generated by workbench/make_charts_data.py from workbench/data/*.json. */
window.RUMI_CHARTS = {
 "01_weekly_trend": {
  "type": "trend",
  "title": "Kalas switched on in April, went quiet from June, and only came back the week we visited",
  "how": "Each dot is one week for the four roster teachers together. Higher means more happened that week. June to August is the summer break. The last week is one day.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "ylabel": "Count",
  "x": [
   "6 Apr",
   "13 Apr",
   "20 Apr",
   "27 Apr",
   "4 May",
   "11 May",
   "18 May",
   "25 May",
   "1 Jun",
   "8 Jun",
   "15 Jun",
   "22 Jun",
   "29 Jun",
   "6 Jul",
   "13 Jul",
   "20 Jul",
   "27 Jul",
   "3 Aug",
   "10 Aug",
   "17 Aug",
   "24 Aug",
   "31 Aug",
   "7 Sep",
   "14 Sep",
   "21 Sep",
   "28 Sep",
   "5 Oct*"
  ],
  "pointLabel": "{series}, week of {x}",
  "series": [
   {
    "name": "Lesson plans made",
    "color": "navy",
    "values": [
     4,
     2,
     1,
     4,
     3,
     0,
     1,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     1,
     0,
     1,
     0,
     0,
     0,
     1,
     5,
     0,
     0,
     0,
     0,
     6
    ],
    "meaning": [
     "4 lesson plans made that week.",
     "2 lesson plans made that week.",
     "1 lesson plans made that week.",
     "4 lesson plans made that week.",
     "3 lesson plans made that week.",
     "0 lesson plans made that week.",
     "1 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "1 lesson plans made that week.",
     "0 lesson plans made that week.",
     "1 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "1 lesson plans made that week.",
     "5 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "0 lesson plans made that week.",
     "6 lesson plans made that week."
    ]
   },
   {
    "name": "AI-coach lessons",
    "color": "orange",
    "values": [
     0,
     1,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     1,
     1,
     0,
     0,
     0,
     1
    ],
    "meaning": [
     "0 lessons recorded for the AI coach that week.",
     "1 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "1 lessons recorded for the AI coach that week.",
     "1 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "0 lessons recorded for the AI coach that week.",
     "1 lessons recorded for the AI coach that week."
    ]
   },
   {
    "name": "Teachers active",
    "color": "green",
    "values": [
     3,
     2,
     1,
     3,
     1,
     0,
     3,
     0,
     0,
     0,
     0,
     0,
     2,
     0,
     3,
     1,
     2,
     0,
     2,
     1,
     3,
     3,
     2,
     1,
     0,
     0,
     4
    ],
    "meaning": [
     "3 of the 4 teachers did anything on Rumi that week.",
     "2 of the 4 teachers did anything on Rumi that week.",
     "1 of the 4 teachers did anything on Rumi that week.",
     "3 of the 4 teachers did anything on Rumi that week.",
     "1 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "3 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "2 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "3 of the 4 teachers did anything on Rumi that week.",
     "1 of the 4 teachers did anything on Rumi that week.",
     "2 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "2 of the 4 teachers did anything on Rumi that week.",
     "1 of the 4 teachers did anything on Rumi that week.",
     "3 of the 4 teachers did anything on Rumi that week.",
     "3 of the 4 teachers did anything on Rumi that week.",
     "2 of the 4 teachers did anything on Rumi that week.",
     "1 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "0 of the 4 teachers did anything on Rumi that week.",
     "4 of the 4 teachers did anything on Rumi that week."
    ]
   }
  ],
  "explain": {
   "5 Oct": {
    "title": "Week of 5 Oct, one day",
    "text": "Monday 6 October only. All four teachers typed MGLP within 25 minutes of each other. 6 plans, 1 coach lesson, 4 teachers active in a single morning."
   },
   "31 Aug": {
    "title": "Week of 31 Aug",
    "text": "The new session's one busy week before the visit: 5 plans and 3 coach lessons, then three quiet weeks."
   }
  }
 },
 "02_per_teacher_plans": {
  "type": "grouped_bar",
  "title": "Two teachers carry the school: Gul and Asima made 20 of 29 plans",
  "how": "Each group is one teacher. Three bars: lesson plans, the multigrade plans from 6 October, and homework bundles. April to October.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "ylabel": "Plans",
  "categories": [
   "Asima",
   "Gul",
   "Nabeela",
   "Salma"
  ],
  "series": [
   {
    "name": "Lesson plans",
    "color": "navy",
    "values": [
     6,
     9,
     2,
     7
    ],
    "meaning": [
     "6 lesson plans since April.",
     "9 lesson plans since April.",
     "2 lesson plans since April.",
     "7 lesson plans since April."
    ]
   },
   {
    "name": "Multigrade plans (6 Oct)",
    "color": "orange",
    "values": [
     3,
     2,
     0,
     0
    ],
    "meaning": [
     "3 multigrade plans, all on 6 October.",
     "2 multigrade plans, all on 6 October.",
     "0 multigrade plans, all on 6 October.",
     "0 multigrade plans, all on 6 October."
    ]
   },
   {
    "name": "Homework bundles",
    "color": "teal",
    "values": [
     3,
     1,
     0,
     5
    ],
    "meaning": [
     "3 homework bundles.",
     "1 homework bundles.",
     "0 homework bundles.",
     "5 homework bundles."
    ]
   }
  ],
  "explain": {
   "Nabeela": "Nabeela changed phone number in August. Both accounts are counted here. 2 lesson plans, no multigrade plans: the picker refused the new number on 6 October.",
   "Salma": "Salma changed phone number in May. Both accounts counted. 7 lesson plans and 5 homework bundles, no multigrade plans until the visit day: the picker refused the new number on 6 October."
  }
 },
 "03_accounts_vs_roster": {
  "type": "bar_h",
  "title": "13 accounts point at Kalas; only 6 belong to its 4 roster teachers",
  "how": "Every account in the database that says it is at Kalas, sorted into what it really is.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "xlabel": "Accounts",
  "labels": [
   "AEO roster teachers (4 people, 6 accounts)",
   "On Khasala Khurd or Hoshial rosters, carrying Kalas's code",
   "Self-entered Khasala Khurd, on no roster",
   "Named multigrade tester, not a Kalas teacher",
   "Never registered, no roster match"
  ],
  "values": [
   6,
   3,
   1,
   1,
   2
  ],
  "colors": [
   "navy",
   "orange",
   "orange",
   "orange",
   "teal"
  ],
  "meaning": [
   "The four real teachers. Two of them have two accounts because they changed number.",
   "Three teachers from the next schools over typed Kalas's code when they registered.",
   "One registered account that typed the Khasala Khurd name with Kalas's code.",
   "A tester the team uses for the multigrade plans.",
   "Two numbers that registered under Kalas and are on no list."
  ],
  "explain": {
   "AEO roster teachers (4 people, 6 accounts)": "Asima, Gul, Nabeela and Salma. Nabeela and Salma each changed phone number, so each has an old and a current account."
  }
 },
 "04_grades_served": {
  "type": "bar_v",
  "title": "Since August: nothing for grades 1 and 4, and the multigrade plans all arrived on 6 October",
  "how": "Lesson plans by grade since 1 August, the four roster teachers. Homework bundles left out.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "ylabel": "Lesson plans",
  "labels": [
   "Grade 1",
   "Grade 2",
   "Grade 3",
   "Grade 4",
   "Grade 5",
   "Free-text",
   "Multigrade (2+3, 4+5)"
  ],
  "values": [
   0,
   1,
   1,
   0,
   4,
   1,
   5
  ],
  "color": "teal",
  "highlight": [
   6
  ],
  "highlightColor": "orange",
  "meaning": [
   "0 plans for grade 1 since August.",
   "1 plans for grade 2 since August.",
   "1 plans for grade 3 since August.",
   "0 plans for grade 4 since August.",
   "4 plans for grade 5 since August.",
   "1 plans for free-text since August.",
   "5 plans for multigrade (2+3, 4+5) since August."
  ],
  "explain": {
   "Multigrade (2+3, 4+5)": "Five multigrade plans, all made on the morning of 6 October by Asima and Gul: maths for grades 2 and 3, English for grades 4 and 5, Urdu for grades 2 and 3."
  }
 },
 "05_benchmark_breadth": {
  "type": "grouped_bar",
  "title": "Breadth is at the ceiling: every Kalas teacher has made a plan and messaged since August",
  "how": "Share of roster teachers who did each thing since 1 August. Kalas against its markaz and against all of Rawalpindi.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "ylabel": "% of teachers",
  "ymax": 100,
  "categories": [
   "Made a lesson plan",
   "Used the AI coach",
   "Messaged Rumi"
  ],
  "series": [
   {
    "name": "GGPS Kalas",
    "color": "orange",
    "values": [
     100,
     75,
     100
    ],
    "meaning": [
     "4 of 4 teachers made a plan.",
     "3 of 4 teachers recorded a lesson.",
     "4 of 4 teachers messaged."
    ]
   },
   {
    "name": "Adyala-Female markaz",
    "color": "navy",
    "values": [
     90.2,
     56.9,
     92.8
    ],
    "meaning": [
     "90.2% across the markaz's 13 schools.",
     "56.9% across the markaz.",
     "92.8% across the markaz."
    ]
   },
   {
    "name": "Rawalpindi",
    "color": "teal",
    "values": [
     75.3,
     59.9,
     87.5
    ],
    "meaning": [
     "75.3% across 270 Rawalpindi schools.",
     "59.9% across Rawalpindi.",
     "87.5% across Rawalpindi."
    ]
   }
  ],
  "explain": {
   "Made a lesson plan": "Kalas 100%, the markaz 90.2%, Rawalpindi 75.3%. Everyone here has tried it."
  }
 },
 "06_benchmark_volume": {
  "type": "grouped_bar",
  "title": "Volume is half the region: 3 plans per teacher since August, against a Rawalpindi median of 6",
  "how": "Per roster teacher since 1 August. Kalas is its actual number; markaz and Rawalpindi are the median school.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "ylabel": "Per teacher",
  "categories": [
   "Lesson plans per teacher",
   "AI-coach lessons per teacher"
  ],
  "series": [
   {
    "name": "GGPS Kalas",
    "color": "orange",
    "values": [
     3.0,
     0.75
    ],
    "meaning": [
     "12 plans across 4 teachers.",
     "3 coach lessons across 4 teachers."
    ]
   },
   {
    "name": "Adyala-Female markaz, median school",
    "color": "navy",
    "values": [
     4.0,
     1.0
    ],
    "meaning": [
     "The middle school in the markaz.",
     "The middle school in the markaz."
    ]
   },
   {
    "name": "Rawalpindi, median school",
    "color": "teal",
    "values": [
     6.0,
     2.0
    ],
    "meaning": [
     "The middle school in Rawalpindi.",
     "The middle school in Rawalpindi."
    ]
   }
  ]
 },
 "07_ai_coach_vs_observation": {
  "type": "grouped_bar",
  "title": "Three AI-coach lessons, zero in-person observations at Kalas",
  "how": "Per teacher since 1 August. In-person means an observation recorded by a coach or AEO who was in the room.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "ylabel": "Lessons",
  "categories": [
   "Asima",
   "Gul",
   "Nabeela",
   "Salma"
  ],
  "series": [
   {
    "name": "AI-coach lessons (self-recorded)",
    "color": "orange",
    "values": [
     0,
     1,
     1,
     1
    ],
    "meaning": [
     "Asima has never recorded a lesson.",
     "One lesson, 3 September.",
     "One lesson, 11 September.",
     "One lesson, 6 October."
    ]
   },
   {
    "name": "In-person observations",
    "color": "navy",
    "values": [
     0,
     0,
     0,
     0
    ],
    "meaning": [
     "None.",
     "None.",
     "None.",
     "None."
    ]
   }
  ],
  "explain": {
   "Asima": "Asima has made 12 plans and 3 multigrade plans but never recorded a lesson in six months."
  }
 },
 "08_hots_goals": {
  "type": "grouped_bar",
  "glossary": true,
  "title": "Student engagement is the weakest goal here, as everywhere; Kalas sits 5 points below the markaz",
  "how": "Each goal as a share of its top mark, averaged over completed AI-coach lessons since 1 August. Click a goal for what it means.",
  "source": "Source: Rumi production database (read-only analyst role) and Axiom. 1 Aug to 6 Oct 2026 unless the chart says otherwise. Pulled 6 Oct 2026.",
  "ylabel": "% of top mark",
  "ymax": 100,
  "categories": [
   "G1",
   "G2",
   "G3",
   "G4",
   "G5"
  ],
  "series": [
   {
    "name": "GGPS Kalas (3 lessons)",
    "color": "orange",
    "values": [
     48,
     33,
     53,
     55,
     68
    ],
    "meaning": [
     "Kalas scored 48% of the top mark.",
     "Kalas scored 33% of the top mark.",
     "Kalas scored 53% of the top mark.",
     "Kalas scored 55% of the top mark.",
     "Kalas scored 68% of the top mark."
    ]
   },
   {
    "name": "Adyala-Female markaz (91 lessons)",
    "color": "navy",
    "values": [
     55.3,
     44.4,
     58.6,
     60.8,
     64.0
    ],
    "meaning": [
     "The markaz scored 55.3%.",
     "The markaz scored 44.4%.",
     "The markaz scored 58.6%.",
     "The markaz scored 60.8%.",
     "The markaz scored 64.0%."
    ]
   },
   {
    "name": "Rawalpindi (2,628 lessons)",
    "color": "teal",
    "values": [
     54.6,
     44.8,
     61.6,
     62.4,
     62.7
    ],
    "meaning": [
     "Rawalpindi scored 54.6%.",
     "Rawalpindi scored 44.8%.",
     "Rawalpindi scored 61.6%.",
     "Rawalpindi scored 62.4%.",
     "Rawalpindi scored 62.7%."
    ]
   }
  ],
  "explain": {
   "G2": "Student engagement: 33% at Kalas, 44% in the markaz, 45% in Rawalpindi. Every Kalas lesson scored 3 of 9 here: no pair work, no second method, no discussion."
  }
 },
 "09_two_phones": {
  "type": "grouped_bar",
  "title": "One lesson, two phones, two rulers: 24 of 48 on hers, 19 of 48 on his",
  "how": "The same sixteen indicators, scored from two phones. Salma's phone went through the self-coach path, which marks each indicator 1 to 3. Sohaib's went through the observer form, which marks 0 to 3.",
  "source": "Source: Rumi's own records of the 7 Oct lesson, Salma's phone and Sohaib's phone. HOTS v1.1.",
  "ylabel": "Area score",
  "ymax": 12,
  "categories": [
   "Assessment & feedback",
   "Student engagement",
   "Lesson planning & content",
   "Instructional strategies (of 12)",
   "Classroom environment"
  ],
  "series": [
   {
    "name": "Salma's phone (self-coach): 50%",
    "color": "orange",
    "values": [
     5,
     3,
     4,
     8,
     4
    ],
    "meaning": [
     "5 of 9.",
     "3 of 9.",
     "4 of 9.",
     "8 of 12.",
     "4 of 9."
    ]
   },
   {
    "name": "Sohaib's phone (observer form): 39.6%",
    "color": "navy",
    "values": [
     4,
     1,
     3,
     8,
     3
    ],
    "meaning": [
     "4 of 9.",
     "1 of 9: two indicators read 0.",
     "3 of 9: one indicator reads 0.",
     "8 of 12.",
     "3 of 9: one indicator reads 0."
    ]
   }
  ],
  "explain": {
   "Student engagement": "3 of 9 on Salma's phone, 1 of 9 on Sohaib's. Both saw the same thing: no pair work, no second method, no discussion. The observer form can give 0, the self path cannot.",
   "Instructional strategies (of 12)": "8 of 12 on both phones. Modelling the method got the top mark on both. This is where the two rulers agree."
  }
 },
 "10_plan_vs_tape": {
  "type": "grouped_bar",
  "title": "The plan asked for 48 minutes in two rotations; the tape holds 16, and the money never came out",
  "how": "Minutes per step as the multigrade plan wrote them, against minutes on Salma's recording. Steps after 15:46 are not on the tape, which is not the same as skipped.",
  "source": "Source: Rumi's own records of the 7 Oct lesson, Salma's phone and Sohaib's phone. HOTS v1.1.",
  "ylabel": "Minutes",
  "categories": [
   "Hook",
   "Rotation 1 (grade 4 taught)",
   "Rotation 2 (grade 5 taught)",
   "You Do (walk & check)",
   "Wrap up + exit ticket"
  ],
  "series": [
   {
    "name": "Planned minutes",
    "color": "teal",
    "values": [
     1,
     15,
     15,
     15,
     2
    ],
    "meaning": [
     "A silent two-answer question with coins.",
     "Teacher with grade 4, money on the table; grade 5 works alone.",
     "Teacher with grade 5, 25p coins; grade 4 works alone.",
     "The teacher walks to each grade and ticks notebooks.",
     "Say it loud, then a three-option ticket."
    ]
   },
   {
    "name": "On the tape",
    "color": "orange",
    "values": [
     1,
     2,
     8,
     2,
     0
    ],
    "meaning": [
     "Salaam and how are you, then a whole-class recall instead.",
     "Same-denominator addition on the board, no coins.",
     "Unlike denominators and LCM, starting at minute 6 not 16.",
     "Practice assigned to each grade, then the phone stops.",
     "Not on the tape."
    ]
   }
  ],
  "explain": {
   "Rotation 1 (grade 4 taught)": "Grade 4 got 1 minute 40 seconds of teaching on the board. The plan gave it 15 minutes with Rs 1 notes and 50p coins on the table.",
   "Wrap up + exit ticket": "The recording ends at 15:46 on 'stop it'. We cannot say the exit ticket was skipped, only that the phone was off."
  }
 }
};
